{{- if .Values.serviceAccounts }}
{{- $total := len .Values.serviceAccounts }}
{{- range $index, $sa := .Values.serviceAccounts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa.name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: ocp-dog
    component: {{ $sa.component | default "shared" }}
{{- if lt $index (sub $total 1) }}
---
{{- end }}
{{- end }}
{{- end }}
